[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
otc = "8X2wDShtcJ5mFrcsJPjK8tQCD16zBqzsUGwhSCM4ggko"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "npx --yes ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

