[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
otc = "EPqRoaDur9VtTKABWK3QQArV2wCYKoN3Zu8kErhrtUxp"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "npx --yes ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

