[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
otc = "6qn8ELVXd957oRjLaomCpKpcVZshUjNvSzw1nc7QVyXc"

[programs.devnet]
otc = "6qn8ELVXd957oRjLaomCpKpcVZshUjNvSzw1nc7QVyXc"

[programs.mainnet]
otc = "6qn8ELVXd957oRjLaomCpKpcVZshUjNvSzw1nc7QVyXc"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "bunx --bun ts-mocha -p ./tsconfig.json -t 1000000 tests/otc.security-audit.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

